Kodeworks/liquidator

src/App.tsx, src/components/FAQ.tsx, src/components/Homepage.tsx, src/components/molecules/Navigation.tsx, src/components/molecules/Page.tsx, src/components/molecules/Toolbar.tsx, src/components/molecules/atoms/Heading.tsx, src/components/molecules/atoms/NavigationBrand.tsx, src/components/molecules/atoms/NavigationPill.tsx, src/components/molecules/atoms/NavigationSeparator.tsx, src/stories/index.js, src/styling/global.ts, src/styling/sizes.ts, src/styling/theme.ts
Implemented page wrapper with some padding and fresh colors to make it a bit easier on the eyes. Also added navigation in the form of a sidebar. 
Do note however that this currently does not work on mobile. However, it is written with that in mind, so converting it should not be that hard.
=> Navigation and basic page wrapper

src/components/molecules/TabMenu.tsx, src/components/molecules/atoms/TabItem.tsx, src/stories/index.js
@FredrikAugust: Gir component-molecule-atom strukturen mening for de to Tab-filene?
=> Made components for Tab navigation

src/components/atoms/__tests__/AddButton.test.tsx
=> Add test for AddButton.tsx

src/components/atoms/TransactionEntry.tsx, src/components/molecules/Filters.tsx, src/components/organism/Transactions.tsx
For now, there are no tests, as the code I'm going to use in the tests come from another pr (#43).
=> Implement the filters currently available.

src/components/atoms/TransactionEntry.tsx, src/components/atoms/__tests__/TransactionEntry.test.tsx, src/components/molecules/Filters.tsx, src/components/molecules/TransactionCalculator.tsx, src/components/molecules/__tests__/Filters.tsx, src/declarations/transaction.ts, src/helpers/transaction_creator.ts, src/stories/index.stories.js
Also changed ITransaction['name'] to ITransaction['description'] to
match that defined in the Swagger API.
Closes #42.
Closes #45.
=> Tested Filters

db.json
- To be used together with [json-server](https://github.com/typicode/json-server#generate-random-data).
- Data can be retrieved from https://my-json-server.typicode.com/kodeworks/liquidator-frontend/
- Data generated with [JSON Generator](https://www.json-generator.com/)
- This should make testing and presenting functionality easier
=> Create db.json with fake data

src/mitochondria/auth.ts, src/mitochondria/balances.ts, src/mitochondria/transactions.ts
=> Make balances.ts::getMonth use new fetch pattern

src/mitochondria/auth.ts, src/mitochondria/balances.ts, src/mitochondria/company.ts, src/mitochondria/index.ts, src/mitochondria/recurring.ts, src/mitochondria/transactions.ts
This is a lot more intuitive, and makes it harder to mess up the query
string :smile:.
=> Use queryString and objects for query parameters

src/components/organism/Toolbar.tsx
=> Added z-index 999 to the toolbar so that nothing shows infront of it

frontend/src/components/atoms/Routes.tsx, frontend/src/components/organism/Navigation.tsx, frontend/src/components/organism/Projections.tsx
This PR fixes #155 
**Also note:**
The FAQ and Balances menu items have been commented out.
=> Created projection page

frontend/src/components/atoms/Routes.tsx, frontend/src/components/molecules/AddTransaction.tsx, frontend/src/mitochondria/index.ts
=> Update error scheme to match backend, and prevent login loop

frontend/src/components/molecules/EditTransaction.tsx, frontend/src/components/organism/Projections.tsx
=> Group transactions by month, and format currency

frontend/src/components/atoms/TransactionEntry.tsx, frontend/src/components/atoms/__tests__/BalancesCalendarEntry.test.tsx, frontend/src/components/molecules/__tests__/BalancesCalendar.test.tsx, frontend/src/helpers/__tests__/currency.test.ts, frontend/src/helpers/currency.ts
=> Update currency formatting to use spaces

frontend/src/components/molecules/AddTransaction.tsx, frontend/src/components/molecules/Form.tsx
Fixes #191.
You can now specify a function as the label, and it will be evaluated the function with the current form values.
=> Dynamic date label

frontend/src/components/atoms/CompanyUser.tsx, frontend/src/components/molecules/Company.tsx, frontend/src/helpers/guardAction.ts
If you want to delete something important, you will now be prompted as to whether you really want to do so or not.
=> You will now be prompted before deletion actions

frontend/src/components/organism/Projections.tsx
=> Projections now use the correct starting value

frontend/src/components/molecules/AddTransaction.tsx, frontend/src/components/molecules/Chart.tsx, frontend/src/components/molecules/Form.tsx, frontend/src/components/organism/Projections.tsx
=> Freeze fields in reset of state Form.tsx, Chart fixes, and Projection handles previous balances

frontend/src/components/atoms/CompanyUser.tsx, frontend/src/components/organism/Navigation.tsx, frontend/src/components/organism/Projections.tsx
- Proper label when leaving company
- Remove company from frontend when leaving a company you're in
- Move projections header up so that it doesn't _leak_ content
- Non-owners should not be able to edit roles of other users
=> Various ux fixes

frontend/src/components/atoms/__tests__/BalancesCalendarEntry.test.tsx, frontend/src/components/atoms/__tests__/TransactionEntry.test.tsx, frontend/src/components/molecules/__tests__/BalancesCalendar.test.tsx, frontend/src/helpers/__tests__/currency.test.ts, frontend/src/helpers/currency.ts
Having decimals in the Projections view is not really useful.
=> Remove decimals from Projections

frontend/src/components/atoms/Input.tsx, frontend/src/components/atoms/UpdateCompanyForm.tsx, frontend/src/components/molecules/AddTransaction.tsx, frontend/src/components/molecules/EditTransaction.tsx, frontend/src/components/molecules/Form.tsx, frontend/src/components/molecules/OverrideRecurringForm.tsx, frontend/src/components/organism/authentication/CreateCompany.tsx, frontend/src/components/pages/Companies.tsx
Add min and max values to number inputs and apply to transactions and company numbers so they cant have incorrect numbers
Fixes #205
=> Validate amounts when working with transactions or company numbers

frontend/src/components/atoms/Button.tsx, frontend/src/components/atoms/CompanyUser.tsx, frontend/src/components/atoms/TransactionEntry.tsx, frontend/src/components/molecules/Company.tsx, frontend/src/components/molecules/EditTransaction.tsx, frontend/src/styling/theme.ts
When hovering on buttons like **Delete company**
=> Add dangerzone buttons and make button texts more intuitive

frontend/src/components/molecules/EditTransaction.tsx
=> Add support for changing transaction type when editing a transaction

frontend/src/helpers/pagination_iterator.ts
=> Add hack to prevent it from querying /api twice
